### ISSUE TITLE
Unable to execute the code

### ISSUE THREAD

**Issue by saijyothi369** [unstabl3/dextros#3]
Hi ,

I am getting the following errors.

Traceback (most recent call last):

File "dextros.py", line 158, in <module>

for line in f:

File "/usr/lib/python3.6/codecs.py", line 321, in decode

(result, consumed) = self._buffer_decode(data, self.errors, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 923: invalid continuation byte

If I changed the dictionary file ...i get rid of the above error but get the following error.
File "dextros.py", line 162, in <module>
    count = (num_lines + (size - 1)) // (size - 1)
ZeroDivisionError: integer division or modulo by zero

Thanks and Regards,
Jyo

**Comment by unstabl3** [comment]
Hi,
I rechecked this! It is working fine for me!

`count = (num_lines + (size - 1)) // (size - 1)
ZeroDivisionError: integer division or modulo by zero`

This error came because you have not installed either mpi4py library or your cluster configuration is not proper! :)

The code will automatically detect the number of systems present in the network. (master and slaves).
If it can't find any systems it will throw the above error!

`for line in f:`

`File "/usr/lib/python3.6/codecs.py", line 321, in decode`

`(result, consumed) = self._buffer_decode(data, self.errors, final)`

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 923: invalid continuation byte`

For this error please check your dictionary. I checked with almost 3-4 different files.. It is working fine as of now!

Closing this as it looks like a configuration bug!

Thanks,
Shubham
